# -*- coding: utf-8 -*-
"""inference.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cOuX-nnBeuoNd-TS2-yfHHaPeotLzJO2
"""

from google.colab import drive
drive.mount('/content/drive')

from transformers import SegformerForSemanticSegmentation
import torch
import os

import cv2
import numpy as np
import matplotlib.pyplot as plt
import torch.nn.functional as F

NUM_LABELS=2
CKPT_DIR = "/content/drive/MyDrive/spill_det/checkpoints"

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

best_model = SegformerForSemanticSegmentation.from_pretrained(
    "nvidia/segformer-b1-finetuned-ade-512-512", num_labels=NUM_LABELS, ignore_mismatched_sizes=True
).to(device)

ckpt = torch.load(os.path.join(CKPT_DIR, "best.pt"), map_location=device)
best_model.load_state_dict(ckpt["model_state"])
best_model.eval()
print("loaded best model, val_mIoU was:", ckpt["best_miou"])



from pycocotools.coco import COCO
from pycocotools import mask as coco_mask

def build_mask(coco, ann_ids, h, w):
    mask = np.zeros((h, w), dtype=np.uint8)
    if not ann_ids:
        return mask
    for ann in coco.loadAnns(ann_ids):
        seg = ann.get("segmentation")
        if not seg:
            continue
        if isinstance(seg, list):
            rle = coco_mask.frPyObjects(seg, h, w)
            if isinstance(rle, list):
                rle = coco_mask.merge(rle)
        elif isinstance(seg["counts"], list):
            rle = coco_mask.frPyObjects(seg, h, w)
        else:
            rle = seg
        m = coco_mask.decode(rle)
        if m.ndim == 3:
            m = m.any(axis=2)
        mask = np.maximum(mask, m.astype(np.uint8))
    return mask

# load the test folder's annotation file once
TEST_DIR = "/content/drive/MyDrive/spill_det/dataset/test"
coco_test = COCO(os.path.join(TEST_DIR, "_annotations.coco.json"))

# build a lookup: filename -> (image_id, ann_ids, height, width)
filename_to_info = {}
for img_id, info in coco_test.imgs.items():
    ann_ids = coco_test.getAnnIds(imgIds=img_id)
    filename_to_info[info["file_name"]] = (ann_ids, info["height"], info["width"])

IMAGENET_MEAN = np.array([0.485, 0.456, 0.406], dtype=np.float32)
IMAGENET_STD = np.array([0.229, 0.224, 0.225], dtype=np.float32)

def predict_image(img_path):
    image = cv2.imread(img_path)

    image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)

    # normalize, same as training
    inp = image.astype(np.float32) / 255.0
    inp = (inp - IMAGENET_MEAN) / IMAGENET_STD
    inp = inp.transpose(2, 0, 1)
    pixel_values = torch.from_numpy(inp).unsqueeze(0).float().to(device)



    with torch.no_grad():
        outputs = best_model(pixel_values=pixel_values)
        logits = F.interpolate(outputs.logits, size=image.shape[:2], mode="bilinear", align_corners=False)
        pred_mask = torch.argmax(logits, dim=1).squeeze(0).cpu().numpy()


            # ground truth mask lookup by filename
    # filename = os.path.basename(img_path)
    # ann_ids, h, w = filename_to_info[filename]
    # gt_mask = build_mask(coco_test, ann_ids, h, w)

    fig, axes = plt.subplots(1, 2, figsize=(14, 5))
    axes[0].imshow(image); axes[0].set_title("image")
    # axes[1].imshow(gt_mask, cmap="gray"); axes[1].set_title("ground truth")
    axes[1].imshow(pred_mask, cmap="gray"); axes[1].set_title("prediction")
    for ax in axes: ax.axis("off")
    plt.show()

# just point this at any test image path
predict_image("/content/drive/MyDrive/spill_det/dataset/test/IMG_4531_JPG.rf.d5622bf9b8e366a19df164bccbb3e063.jpg")

!ls /content/drive/MyDrive/spill_det/dataset/test/

predict_image("/content/drive/MyDrive/spill_det/dataset/test/Screenshot-2025-08-06-195933_png.rf.49cc0e2dbcab01b1ca260d54fc89c4a6.jpg")

predict_image("/content/drive/MyDrive/spill_det/dataset/test/vlcsnap-2022-08-11-03h28m31s977_png.rf.bbb44910da0892f0586eb6d89cb66740.jpg")

predict_image("/content/drive/MyDrive/spill_det/dataset/test/Video-shows-the-moment-a-Wentzville-day-care-flooded-during-storms-KSDK-News-1080p-_mp4-0719_jpg.rf.31048604f6e3dffcd4240570756b721b.jpg")

predict_image("/content/drive/MyDrive/spill_det/dataset/test/w8_jpg.rf.153c7376ef23ed2f32c34a3b926b78b1.jpg")

predict_image("/content/drive/MyDrive/spill_det/dataset/test/nmeddter_png.rf.ae9caf64f63f53fce4034e6f645ac887.jpg")

predict_image("/content/drive/MyDrive/spill_det/dataset/test/4e02a3b4-IMG-20241229-WA0186_jpg.rf.cd36cc17fe0ad9ded78b5f9bad5f75f1.jpg")

!ls "/content/drive/MyDrive/spill_det/dataset/Random_Images/"

predict_image("/content/drive/MyDrive/spill_det/dataset/Random_Images/images (3).jpg")

predict_image("/content/drive/MyDrive/spill_det/dataset/Random_Images/images (4).jpg")

predict_image("/content/drive/MyDrive/spill_det/dataset/Random_Images/images (5).jpg")

!ls "/content/drive/MyDrive/spill_det/dataset/Random_Images/"

IMAGENET_MEAN = np.array([0.485, 0.456, 0.406], dtype=np.float32)
IMAGENET_STD = np.array([0.229, 0.224, 0.225], dtype=np.float32)

def predict_image(img_path):
    image = cv2.imread(img_path)

    image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)

    # normalize, same as training
    inp = image.astype(np.float32) / 255.0
    inp = (inp - IMAGENET_MEAN) / IMAGENET_STD
    inp = inp.transpose(2, 0, 1)
    pixel_values = torch.from_numpy(inp).unsqueeze(0).float().to(device)



    with torch.no_grad():
        outputs = best_model(pixel_values=pixel_values)
        logits = F.interpolate(outputs.logits, size=image.shape[:2], mode="bilinear", align_corners=False)
        pred_mask = torch.argmax(logits, dim=1).squeeze(0).cpu().numpy()


        return image, pred_mask

image,  pred_mask = predict_image("/content/drive/MyDrive/spill_det/dataset/test/-_20251111211947_92_84_jpg.rf.ffee8785c609146bbad9c9cb4f5b7112.jpg")

def draw_segmentation_overlay(image, pred_mask, class_name="spill", color=(255, 0, 0), alpha=0.5):
    output = image.copy()
    colored_mask = np.zeros_like(image)
    colored_mask[pred_mask == 1] = color

    output = cv2.addWeighted(output, 1.0, colored_mask, alpha, 0)

    # label the mask - place text near its centroid
    ys, xs = np.where(pred_mask == 1)
    if len(xs) > 0:
        cx, cy = int(xs.mean()), int(ys.mean())
        cv2.putText(output, class_name, (cx, cy),
                    cv2.FONT_HERSHEY_SIMPLEX, 0.7, color, 2)

    return output

labeled_img = draw_segmentation_overlay(image, pred_mask)

    fig, axes = plt.subplots(1, 3, figsize=(18, 5))
    axes[0].imshow(image); axes[0].set_title("image")
    axes[1].imshow(pred_mask, cmap="gray"); axes[1].set_title("prediction mask")
    axes[2].imshow(labeled_img); axes[2].set_title("labele")
    for ax in axes: ax.axis("off")
    plt.show()

image,  pred_mask = predict_image("/content/drive/MyDrive/spill_det/dataset/test/0c1ef9a8-IMG-20241229-WA0038_jpg.rf.07a0137b8c0f8603c37c169fd11b7837.jpg")

labeled_img = draw_segmentation_overlay(image, pred_mask)

fig, axes = plt.subplots(1, 3, figsize=(18, 5))
axes[0].imshow(image); axes[0].set_title("image")
axes[1].imshow(pred_mask, cmap="gray"); axes[1].set_title("prediction mask")
axes[2].imshow(labeled_img); axes[2].set_title("labeled")
for ax in axes: ax.axis("off")
plt.show()

image,  pred_mask = predict_image("/content/drive/MyDrive/spill_det/dataset/test/1_-444-_jpg.rf.f02a449b59fc9d25c8e0f6a9f56bea4a.jpg")

labeled_img = draw_segmentation_overlay(image, pred_mask)

fig, axes = plt.subplots(1, 3, figsize=(18, 5))
axes[0].imshow(image); axes[0].set_title("image")
axes[1].imshow(pred_mask, cmap="gray"); axes[1].set_title("prediction mask")
axes[2].imshow(labeled_img); axes[2].set_title("labeled")
for ax in axes: ax.axis("off")
plt.show()



image,  pred_mask = predict_image("/content/drive/MyDrive/spill_det/dataset/test/0c1ef9a8-IMG-20241229-WA0038_jpg.rf.07a0137b8c0f8603c37c169fd11b7837.jpg")

labeled_img = draw_segmentation_overlay(image, pred_mask)

fig, axes = plt.subplots(1, 3, figsize=(18, 5))
axes[0].imshow(image); axes[0].set_title("image")
axes[1].imshow(pred_mask, cmap="gray"); axes[1].set_title("prediction mask")
axes[2].imshow(labeled_img); axes[2].set_title("labeled")
for ax in axes: ax.axis("off")
plt.show()

!ls /content/drive/MyDrive/spill_det/dataset/valid



import os
import numpy as np
import cv2
import torch
import torch.nn.functional as F
from pycocotools.coco import COCO
from pycocotools import mask as coco_mask

IMAGENET_MEAN = np.array([0.485, 0.456, 0.406], dtype=np.float32)
IMAGENET_STD = np.array([0.229, 0.224, 0.225], dtype=np.float32)

TEST_DIR = "/content/drive/MyDrive/spill_det/dataset/test"
coco_test = COCO(os.path.join(TEST_DIR, "_annotations.coco.json"))

def build_mask(coco, ann_ids, h, w):
    mask = np.zeros((h, w), dtype=np.uint8)
    if not ann_ids:
        return mask
    for ann in coco.loadAnns(ann_ids):
        seg = ann.get("segmentation")
        if not seg:
            continue
        if isinstance(seg, list):
            rle = coco_mask.frPyObjects(seg, h, w)
            if isinstance(rle, list):
                rle = coco_mask.merge(rle)
        elif isinstance(seg["counts"], list):
            rle = coco_mask.frPyObjects(seg, h, w)
        else:
            rle = seg
        m = coco_mask.decode(rle)
        if m.ndim == 3:
            m = m.any(axis=2)
        mask = np.maximum(mask, m.astype(np.uint8))
    return mask

# ---- run over every test image, accumulate global TP/FP/FN ----
total_tp, total_fp, total_fn, total_tn = 0, 0, 0, 0
per_image_ious = []

best_model.eval()
with torch.no_grad():
    for img_id, info in coco_test.imgs.items():
        img_path = os.path.join(TEST_DIR, info["file_name"])
        image = cv2.imread(img_path)
        image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)

        ann_ids = coco_test.getAnnIds(imgIds=img_id)
        gt_mask = build_mask(coco_test, ann_ids, info["height"], info["width"])

        inp = image.astype(np.float32) / 255.0
        inp = (inp - IMAGENET_MEAN) / IMAGENET_STD
        inp = inp.transpose(2, 0, 1)
        pixel_values = torch.from_numpy(inp).unsqueeze(0).float().to(device)

        outputs = best_model(pixel_values=pixel_values)
        logits = F.interpolate(outputs.logits, size=gt_mask.shape, mode="bilinear", align_corners=False)
        pred_mask = torch.argmax(logits, dim=1).squeeze(0).cpu().numpy()

        pred_c = (pred_mask == 1)
        gt_c = (gt_mask == 1)

        tp = np.logical_and(pred_c, gt_c).sum()
        fp = np.logical_and(pred_c, ~gt_c).sum()
        fn = np.logical_and(~pred_c, gt_c).sum()
        tn = np.logical_and(~pred_c, ~gt_c).sum()

        total_tp += tp
        total_fp += fp
        total_fn += fn
        total_tn += tn

        union = tp + fp + fn
        if union > 0:
            per_image_ious.append(tp / union)

# ---- final metrics ----
precision = total_tp / (total_tp + total_fp) if (total_tp + total_fp) > 0 else float("nan")
recall = total_tp / (total_tp + total_fn) if (total_tp + total_fn) > 0 else float("nan")
miou_global = total_tp / (total_tp + total_fp + total_fn)
miou_per_image = np.mean(per_image_ious)
f1 = 2 * precision * recall / (precision + recall)
pixel_accuracy = (total_tp + total_tn) / (total_tp + total_fp + total_fn + total_tn)

print(f"Test images evaluated: {len(coco_test.imgs)}")
print(f"Precision:        {precision:.4f}")
print(f"Recall:           {recall:.4f}")
print(f"F1 score:         {f1:.4f}")
print(f"mIoU (global):    {miou_global:.4f}")
print(f"mIoU (per-image): {miou_per_image:.4f}")
print(f"Pixel accuracy:   {pixel_accuracy:.4f}")